### ISSUE TITLE
Bug | EMS MDT | Profiles

### ISSUE THREAD

**Issue by Xandrice** [Project-Sloth/ps-mdt#89] opened 2022-07-27 03:29 UTC
When accessing MDT profiles on the EMS side, the photo loads in the thumbnail, but doesn't seem to carry it over when you select the player.
Any notes that you try to write in the larger box, don't seem to save either. 

EMS Side: https://i.imgur.com/PdKgcb1.png
PD Side: https://i.imgur.com/47xym2d.png

**Comment by bORNzu** [comment] 2022-09-03 03:29
I'm also having this issue

**Comment by rpRIGGS** [comment] 2022-09-08 14:49
This is still an issue as of now. Anyone have a fix for this yet?

**Comment by JoeSzymkowiczFiveM** [comment] 2022-10-21 16:52
EMS and Police reports are supposed to have different profile pictures by design. I feel like this was half-way broken at one point, and I will fix the search results.

**Comment by MonkeyWhisper** [comment] 2023-01-30 08:14
https://github.com/Project-Sloth/ps-mdt/pull/116

**Closed as completed by MonkeyWhisper** 2023-01-30 08:14 UTC
Labels: bug
